### ISSUE TITLE
Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by Tustin** [komefai/PS4RemotePlayInterceptor#1]
This project looks awesome and is something I was wanting to do myself a while back but never got around to it. I wanted to try this out but I'm getting an exception when trying to inject:
```
Failed to inject to target: Exception has been thrown by the target of an invocation.
```
I get that error when calling `Interceptor.Inject();`, because using `Interceptor.Watchdog.Start();` never actually injects. I'm guessing this has something to do with EasyHook but I'm not sure what it could be. 

Any ideas?

Edit: forgot to mention that Remote Play is running beforehand and I used NuGet to pull in the project.

**Comment by Tustin** [comment]
I decided to just clone this project manually and run the demo project you made, and using a breakpoint I managed to find the actual exception:
`{"Failed to connect to an IPC Port: The system cannot find the file specified.\r\n "}`

I don't know anything about IPC but I'll see if I can find anything based on the error.

**Comment by komefai** [comment]
@Tustin Hi, thanks for trying out the library!

I'm not familiar with this exception message but it is probably coming from EasyHook as you've guessed. However that specific try/catch block handles a generic Exception type, so to narrow it down it would be best to inspect the InnerException in the exception details.

You can try cloning the project and run PS4RemotePlayInterceptorDemo as it also manually uses `Interceptor.Inject()` as well. Also a classic troubleshooting for EasyHook is to try run the program as administrator.

Let me know if this helps! Feel free to include any screenshots you think might helped.

**Comment by komefai** [comment]
Whoops didn't see your second comment there. Thanks again, I'll look into it.

**Comment by Tustin** [comment]
Haha, good timing! Just let me know if you find anything. It's probably just something weird on my PC that's causing it to fail. I'm no stranger to weird stuff like that happening on projects I make 😛. I'll mess with some stuff too to see if I can figure anything out.

**Comment by komefai** [comment]
@Tustin Actually I did make a change on creating IPC server on v0.3.0+ to support the Watchdog which might be the cause. 

I guess you can try `Install-Package PS4RemotePlayInterceptor -Version 0.2.1` which uses the default IPC parameters straight from EasyHook's tutorial that are known to work for most people.

**Comment by Tustin** [comment]
@komefai You are a saint! That version works just fine for me. Very weird that the newer one just doesn't work. If you want to look into it, the exception was being thrown from EasyHook here:
https://github.com/komefai/PS4RemotePlayInterceptor/blob/master/PS4RemotePlayInterceptor/Classes/Interceptor.cs#L77

Not a big deal for me because I was just planning on using the manual Inject method anyways.

**Comment by komefai** [comment]
@Tustin Awesome! Glad that it helped. I might have a variable to switch to the old injection method for incompatible machines if it cannot be fixed from our end.

EDIT: You can now use "Compatibility" mode in v0.4.1

```chsarp
// Setup callback to interceptor
Interceptor.Callback = new InterceptionDelegate(OnReceiveData);

// Inject
Interceptor.InjectionMode = InjectionMode.Compatibility;
Interceptor.Inject();
```
